env:
  es6: true
  node: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:prettier/recommended'
  - 'plugin:jsx-a11y/recommended'
  -  plugin:react/recommended
  - 'prettier/@typescript-eslint'
  -  prettier/react
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2018
  sourceType: module
plugins:
  - '@typescript-eslint'
  - "react-hooks"
  - 'jsx-a11y'
rules:
  prettier/prettier:
    - error
    -
      trailingComma: all
      singleQuote: true
      printWidth: 100
      semi: true
  '@typescript-eslint/explicit-function-return-type': off
  '@typescript-eslint/interface-name-prefix': off
  '@typescript-eslint/no-explicit-any': off
  '@typescript-eslint/no-namespace': off
  '@typescript-eslint/no-unused-vars':
    - warn
    -
      argsIgnorePattern: '^_'
      varsIgnorePattern: '^_'
  '@typescript-eslint/no-use-before-define': off
  '@typescript-eslint/explicit-module-boundary-types': off
  'camelcase': error

  eqeqeq:
    - "error"
    - "always"
settings:
  react:
    version: "detect"